python -m newvgg16 \
    --vgg_config VGG16_standard \
    --activation relu \
    --loss_fn cross_entropy \
    --optimizer sgd \
    --lr 0.01 \
    --momentum 0.9 \
    --weight_decay 1e-4 \
    --epochs 10 \
    --batch_size 128 \
    --num_workers 2 \